### ISSUE TITLE
Add -json output flag

### ISSUE THREAD

**Issue by lmilbaum** [icholy/gomajor#24]
Would it be possible to make this package improtable?

**Comment by lmilbaum** [comment]
> I do not plan on exposing a public api for this project. However, I could be persuaded to add a `-json` flag if you wish to invoke the tool programmatically.

Yes. Please.

**Comment by lmilbaum** [comment]
It would be helpful if the list command json output can include the the latest available version of a specific package.

**Comment by icholy** [comment]
@lmilbaum currently, the `gomajor list` command doesn't let you query a specific package. Do you have an idea of how you'd want that to work? Would it take an optional list of module names?

```
gomajor list github.com/google/go-github/v3
```

**Comment by icholy** [comment]
I've added the option to provide a list of module paths to the `list` sub-command in 49c4dd47a90f91a0c3d60a11a468e2b754f3d179

**Comment by icholy** [comment]
I've published `v0.10.0` with the new features.

**Comment by lmilbaum** [comment]
Thank you so much for the quick turnaround
