### ISSUE TITLE
Support GOPROXY env var

### ISSUE THREAD

**Issue by icholy** [icholy/gomajor#35]
Add support for the `GOPROXY` environment variable.

Split from: https://github.com/icholy/gomajor/issues/18#issuecomment-2214262487

**Comment by icholy** [comment]
@sanyatuning can you test this branch?

**Comment by icholy** [comment]
@sanyatuning let me know if this is working for you.

**Comment by sanyatuning** [comment]
It is working fine. Thank you for your help
