### ISSUE TITLE
Wrong latest reported for stripe-go (skipped version problem?)

### ISSUE THREAD

**Issue by KenjiTakahashi** [icholy/gomajor#37]
The latest version reported for https://pkg.go.dev/github.com/stripe/stripe-go is `v76`. The actual latest is `v80` (at the time of writing).
Might be worth noting that `v77` doesn't exist. This might be tripping the tool.

**Comment by icholy** [comment]
Yeah, unfortunately that's a limitation of the tool. It's currently noted here: https://github.com/icholy/gomajor?tab=readme-ov-file#warning

> The latest version will not be found if there are gaps between major version numbers.

The module proxy doesn't provide a way to query all major versions of a module, so this tool is forced to incrementally check the existence of each version.

**Comment by icholy** [comment]
See the 5 comments starting here: https://github.com/golang/go/issues/40323#issuecomment-678358697

**Comment by KenjiTakahashi** [comment]
Ach, I somehow missed that warning line, sorry! I even participated in that issue myself, albeit later on than this :-).
I guess feel free to close this, then, as it's not actionable ATM.

**Comment by icholy** [comment]
FWIW, it looks like we're finally going to get built-in support for listing new major versions: https://github.com/golang/go/issues/67420
