### ISSUE TITLE
Add -alias flag to auto-add replace directive

### ISSUE THREAD

**Issue by pkieltyka** [icholy/gomajor#7]
Nice tool.

I was thinking .. as you’ve seen discussion at 44550, I need to try it, but a replace of a SIV to one without may help bandaid the experience I’m suggesting in that proposal. What if this tool had -alias which you could pass a package name without SIV and it would add replace to alias. Then could add -alias-all to alias every module without passing a specific one.. and maybe -alias-skip too for exclusion.

I usually use Makefiles, so something like that could be used to manage an experience similar to what I’m describing in 44550. What do you think?

Cc @zikaeroh

**Comment by pkieltyka** [comment]
hmm, I realize this won't work. We need 44550 to happen to create a reasonable experience

**Comment by icholy** [comment]
I wasn't sure how to handle replace directives, so I didn't. This tool completely ignores any `go.mod` entries with a replace directive. I'll look into it though.
